language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t shidhu23/docker-react -f Dockerfile.dev .
scripts:
    - docker run -e CI=true shidhu23/docker-react npm run test